project_id = "qqwljebhdaaeotjlvjic"

[functions.deepseek-medical]
verify_jwt = true

[functions.calendar-feed]
verify_jwt = false

[functions.research-ai]
verify_jwt = true

[functions.pubmed-search]
verify_jwt = true

[functions.statistics-ai]
verify_jwt = true

[functions.fetch-news]
verify_jwt = true

[functions.send-notification]
verify_jwt = true
